version: '3.8'

services:
  lstm-server:
    image: tensorflow/serving
    container_name: lstm-server
    ports:
      - "8501:8501"
    volumes:
      - ./lstm_stock/:/models/lstm_stock
    environment:
      - MODEL_NAME=lstm_stock
    networks:
      - jaringanku

  streamlit_stock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_stock
    ports:
      - "8502:8502"
    networks:
      - jaringanku

networks:
  jaringanku:
    driver: bridge
