version: '3'

services:
  stock-forecast:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./home-page-stock-prediction:/app/home-page-stock-prediction
    networks:
      - jaringanku
    
networks:
  jaringanku:
    driver: bridge